---
title: "Introducción"
author: "Arnau López Rodrigo"
date: "2025-04-11"
output: html_document
---

En el proyecto que nos disponemos a presentar, hemos recibido una cantidad de 
tickets de Mercadona (aunque pueden haber habido errores en la recopilación de
estos), los cuales hemos importado y hemos guardado toda su información en data
frames en RStudio.
A partir de ellos, haremos un análisis exploratorio para responder a algunas de
las preguntas más comunes que uno se podría hacer cuando piensa en datos y
características de un supermercado.

Dividiremos la info en dos data frames:
En uno, guardaremos info de cada compra (número de factura, fecha, población del
supermercado).
(ADJUNTAMOS EJEMPLO)

En el otro guardaremos todos los productos, con la cantidad que se compra de 
cada uno, el precio etc.
(ADJUNTAMOS EJEMPLO)

Dada la vista información, el profesor nos ha planteado las siguientes preguntas:
¿Cuáles son los 5 productos, de los vendidos por unidades, con más ventas ? 
¿Cuántas unidades de cada uno se han vendido ?
Si consideramos la categoría de FRUTAS Y VERDURAS. Cuáles son los 5 productos más
vendidos ?
¿Cuántos kilos se han vendido de cada uno de estos productos ?
Si consideramos la categoría de PESCADO. Cuáles son los 5 productos más vendidos? 
¿Cuántos kilos se han vendido de cada uno de estos productos ?
Muestra mediante un gráfico de líneas como ha variado el precio por kilo de las 
bananas y los plátanos en los tickets disponibles, a lo largo del tiempo.
¿ Cuál es la procedencia de los tickets ?
¿ Qué ciudad/ pueblo tiene un mayor número de tickets ?
Muestra mediante un diagrama el número de tickets recogidos cada día de las semana.
¿Si tuvieses que cerrar un día entre semana qué día lo harías?

Y nosotros nos hemos planteado las siguientes:

¿Cuál es el gasto medio por compra?
¿Cuál ha sido la evolución del precio del aceite con el paso del tiempo?
¿Cuál es el mercadona más popular de Valencia? Es decir,¿Cuál ha sido el más
visitado?
¿En qué parte del día es más común hacer la compra?
¿Cuál es el producto que, cuando se compra, se compra en mayor cantidad?


En esta primera fase del proyecto, hemos aprendido a importar documentos pdf 
así como almacenar de forma iterativa en dfs información de ficheros.
Hemos mejorado nuestro uso en librerías como stringr, y el uso de github
para poder trabajar de forma remota y compartir un repositorio haciendo uso del
"version control".
